"""Interactive forecast dashboard.

Pick a slice of the business (company-wide, by store, by product), choose a
model, and see the hold-out forecast vs actuals with accuracy metrics.

Run:  streamlit run dashboard.py
"""
from __future__ import annotations

import os

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from src.evaluate import backtest
from src.generate_data import main as generate
from src.models import (
    ETSForecaster,
    LightGBMForecaster,
    SARIMAForecaster,
    SeasonalNaiveForecaster,
    prophet_available,
)
from src.run_experiment import build_series, load_sales

st.set_page_config(page_title="Demand Forecasting", page_icon="📈", layout="wide")

MODEL_FACTORY = {
    "SARIMA": SARIMAForecaster,
    "SeasonalNaive": SeasonalNaiveForecaster,
    "ETS(Holt-Winters)": ETSForecaster,
    "LightGBM": LightGBMForecaster,
}
if prophet_available():
    from src.models import ProphetForecaster

    MODEL_FACTORY["Prophet"] = ProphetForecaster


@st.cache_data
def _data() -> pd.DataFrame:
    if not os.path.exists("data/sales.csv"):
        generate()
    return load_sales()


df = _data()

st.title("📈 Demand / Sales Forecasting")
st.caption("Forecast accuracy on a 28-day hold-out. Lower MAPE is better.")

col1, col2, col3, col4 = st.columns(4)
store = col1.selectbox("Store", ["All"] + sorted(df["store"].unique()))
product = col2.selectbox("Product", ["All"] + sorted(df["product"].unique()))
model_name = col3.selectbox("Model", list(MODEL_FACTORY))
horizon = col4.slider("Forecast horizon (days)", 7, 56, 28, step=7)

series = build_series(
    df,
    store=None if store == "All" else store,
    product=None if product == "All" else product,
)

with st.spinner(f"Fitting {model_name}…"):
    res = backtest(series, MODEL_FACTORY[model_name](), horizon=horizon)

m1, m2, m3, m4 = st.columns(4)
m1.metric("MAPE", f"{res.metrics['MAPE']}%")
m2.metric("RMSE", res.metrics["RMSE"])
m3.metric("MAE", res.metrics["MAE"])
m4.metric("sMAPE", f"{res.metrics['sMAPE']}%")

history = series.iloc[-90:-horizon]
fig = go.Figure()
fig.add_trace(go.Scatter(x=history.index, y=history["sales"], name="History", line=dict(color="#888")))
fig.add_trace(go.Scatter(x=res.test_index, y=res.y_true, name="Actual", line=dict(color="#222", width=3)))
fig.add_trace(go.Scatter(x=res.test_index, y=res.y_pred, name=f"Forecast ({model_name})", line=dict(color="#d6336c", width=3, dash="dash")))
fig.update_layout(height=480, xaxis_title="Date", yaxis_title="Units / day", legend=dict(orientation="h"))
st.plotly_chart(fig, use_container_width=True)

with st.expander("About this dataset"):
    st.write(
        "Synthetic daily retail demand with trend, weekly + yearly seasonality, "
        "holidays and promotions. Generated by `src/generate_data.py` — no external data."
    )
